encoder: samba_asr
encoder_conf:
  output_size: 512          # FIXED: Giảm từ 768 -> 512 để stability
  num_layers: 6             # FIXED: Giảm từ 12 -> 6 layers ban đầu
  d_state: 16
  d_conv: 4
  expand: 2
  dropout_rate: 0.1
  input_layer: conv2d
  pos_enc_layer_type: abs_pos
  normalize_before: true

decoder: samba_asr_decoder
decoder_conf:
  num_blocks: 4            # FIXED: Giảm từ 6 -> 4 blocks
  d_state: 16
  d_conv: 4
  expand: 2
  dropout_rate: 0.1
  positional_dropout_rate: 0.1
  normalize_before: true
  use_output_layer: true

model_conf:
  lsm_weight: 0.1

frontend: default
frontend_conf:
  n_fft: 512
  win_length: 400
  hop_length: 160
  n_mels: 80
  fmin: 0
  fmax: 8000

# FIXED: Optimization settings cho stability
optim: adamw
optim_conf:
  lr: 0.00005                # FIXED: Giảm LR từ 0.0001 -> 0.00005
  betas: [ 0.9, 0.98 ]       # FIXED: Thay đổi beta2 từ 0.999 -> 0.98
  eps: 1.0e-06               # FIXED: Tăng eps từ 1e-08 -> 1e-06
  weight_decay: 0.01

scheduler: warmuplr            # FIXED: Thay scheduler đơn giản hơn
scheduler_conf:
  warmup_steps: 1000

# FIXED: Training configuration cho stability
batch_type: numel
batch_bins: 1000000
accum_grad: 2                # FIXED: Tăng gradient accumulation
grad_clip: 0.5               # FIXED: Giảm grad clip từ 1.0 -> 0.5
grad_noise: false
sort_in_batch: descending
sort_batch: descending
max_epoch: 80


specaug: specaug
specaug_conf:
   apply_time_warp: true
   time_warp_window: 5
   time_warp_mode: bicubic
   apply_freq_mask: true
   freq_mask_width_range:
     - 0
     - 30
   num_freq_mask: 2
   apply_time_mask: true
   time_mask_width_range:
     - 0
     - 40
   num_time_mask: 2

num_workers: 4
log_interval: 10             # FIXED: Tăng tần suất log để theo dõi
keep_nbest_models: 5         # FIXED: Giảm số models keep
nbest_averaging_interval: 0

token_type: char
bpemodel: null

patience: null
early_stopping_criterion: validation
best_model_criterion:
  - - valid
    - acc
    - max
val_scheduler_criterion:
  - - valid
    - loss
    - min

# FIXED: Bật mixed precision với stability
use_amp: true                # FIXED: Thử bật AMP với Samba
cudnn_benchmark: false
cudnn_deterministic: true    # FIXED: Bật deterministic

seed: 777
num_iters_per_epoch: null
log_level: INFO