encoder: samba_asr
encoder_conf:
  output_size: 512
  num_layers: 6
  d_state: 16
  d_conv: 4
  expand: 2
  dropout_rate: 0.1
  input_layer: conv2d
  pos_enc_layer_type: abs_pos
  normalize_before: true

decoder: samba_asr_decoder
decoder_conf:
  num_blocks: 4
  d_state: 16
  d_conv: 4
  expand: 2
  dropout_rate: 0.1
  positional_dropout_rate: 0.1
  normalize_before: true
  use_output_layer: true

model_conf:
  lsm_weight: 0.1

frontend: default
frontend_conf:
  n_fft: 512
  win_length: 400
  hop_length: 160
  n_mels: 80
  fmin: 0
  fmax: 8000

# FIXED: Optimization for ASR1
optim: adamw
optim_conf:
  lr: 0.0002                 # FIXED: Tăng LR vì batch nhỏ
  betas: [ 0.9, 0.98 ]
  eps: 1.0e-06
  weight_decay: 0.01

scheduler: warmuplr
scheduler_conf:
  warmup_steps: 2000         # FIXED: Tăng warmup cho nhiều batches

# FIXED: Batch configuration for ASR1 + numel
batch_type: numel
batch_bins: 10000000         # FIXED: Tăng từ 1M -> 10M (ASR1 với numel cần lớn hơn)
accum_grad: 1                # FIXED: Bỏ accumulation để faster iteration
grad_clip: 1.0               # FIXED: Tăng grad clip
grad_noise: false
sort_in_batch: descending
sort_batch: descending
max_epoch: 50                # FIXED: Giảm epochs vì nhiều iterations/epoch

# FIXED: Reduce augmentation overhead
specaug: specaug
specaug_conf:
   apply_time_warp: false    # FIXED: Tắt time warp cho speed
   apply_freq_mask: true
   freq_mask_width_range:
     - 0
     - 20                    # FIXED: Giảm mask size
   num_freq_mask: 1
   apply_time_mask: true
   time_mask_width_range:
     - 0
     - 30
   num_time_mask: 1

num_workers: 8               # FIXED: Tăng workers cho nhiều small batches
log_interval: 100            # FIXED: Giảm log frequency
keep_nbest_models: 3
nbest_averaging_interval: 0

token_type: char
bpemodel: null

patience: 10                 # FIXED: Early stopping
early_stopping_criterion: validation
best_model_criterion:
  - - valid
    - acc
    - max
val_scheduler_criterion:
  - - valid
    - loss
    - min

# FIXED: Optimize for speed
use_amp: true
cudnn_benchmark: true        # FIXED: Enable benchmark
cudnn_deterministic: false   # FIXED: Disable for speed

seed: 777
num_iters_per_epoch: null
log_level: INFO

# FIXED: Add validation settings
valid_interval: 1000         # Validate every 1000 iterations
save_interval: 2000          # Save every 2000 iterations