# ESPnet2 ASR Training Configuration - Samba ASR (sửa tham số không hợp lệ)

# Samba ASR Encoder - giữ nguyên model
encoder: samba_asr
encoder_conf:
    output_size: 768
    num_layers: 12
    d_state: 16
    d_conv: 4
    expand: 2
    dropout_rate: 0.1

# Samba ASR Decoder - giữ nguyên model
decoder: samba_asr_decoder
decoder_conf:
    num_blocks: 6
    d_state: 16
    d_conv: 4
    expand: 2
    dropout_rate: 0.1

# Model configuration - sử dụng model_conf như config mẫu
model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1

# Frontend - cần thêm frontend type
frontend: default
frontend_conf:
    n_fft: 512
    win_length: 400
    hop_length: 160
    n_mels: 80

# Training configuration
seed: 777
num_workers: 4
batch_type: numel
batch_bins: 5000000
max_epoch: 80
use_amp: true

# Optimizer
optim: adamw
optim_conf:
    lr: 0.0001
    weight_decay: 0.01

# Scheduler
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 10000

# SpecAug
specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    apply_freq_mask: true
    freq_mask_width_range: [0, 30]
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range: [0, 40]
    num_time_mask: 2

# Model selection - sửa format
best_model_criterion:
    - valid
    - acc
    - max
keep_nbest_models: 10

# Token type - cần thiết
token_type: char

# Thêm các tham số bắt buộc tối thiểu
model: espnet
token_list: data/token_list/char/tokens.txt